name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: restart pm2 on server
      uses: appleboy/ssh-action@v0.0.6
      script: |
          export PATH="$(yarn global bin):$PATH"
          cd /home/admin/web/dev.shoes-bags.ru/public_html
          git pull
          yarn
          yarn build
          pm2 restart all
