name: cd

on: [push, pull_request]

publish_dir: ./dist

jobs:
  cd:
    runs-on: ubuntu-latest

  steps:
    - name: Install dependencies
      run: yarn

    - name: Generate
      run: yarn run generate
    
    - name: Deploy
        with:
          publish_dir: ./dist
